SELECT TOP (1000) [ProductID]
      ,[CategoryID]
      ,[ProductName]
      ,[UnitPrice]
      ,[ProductPicture]
      ,[UnitInStock]
      ,[CreatedDate]
      ,[ModifiedDate]
  FROM [smartinvdb].[dbo].[products]